apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: g2yw8q231-go 
  janus-idp.io/tekton: g2yw8q231-go
  backstage.io/kubernetes-id: g2yw8q231-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g2yw8q231-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml